/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://w5574xwipbd4tfluh7ml5yfb4i.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-o4fhkc25rnc3zky2qmnprqzfsq",
    "API": {
        "GraphQL": {
            "endpoint": "https://w5574xwipbd4tfluh7ml5yfb4i.appsync-api.us-east-2.amazonaws.com/graphql",
            "region": "us-east-2",
            "defaultAuthMode": "apiKey",
            "apiKey": "da2-rlu6lhic7bawtptwvbqsmd76sm"
        }
    }
};


export default awsmobile;
